### ISSUE TITLE
HRTechに関して意見交換させてください

### ISSUE THREAD

**Issue by TsubasaK111** [TAKAKING22/team-resume#1]
## 会社名
[株式会社ギブリー](http://givery.co.jp)

## 担当者氏名
近藤　翔

## 条件

雇用形態は目的ありきで、柔軟に対応します。
契約社員（フリーランス）等

## コメント

お世話になります、  
ギブリーでエンジニア・プロジェクトマネージャーをしています近藤と申します。  
  
弊社はエンジニアの成長や採用に関わる事業を長年行なっており、  
今後エンジニア志望学生や新入社員の研修領域に進出したいと考えています。

自分自身も「顧客と向き合い、仮説を検証して行きながら本質的に良い物作りをする」のが大好きで、 
 
それを達成すべくXPやlean、design thinking等の手法を開発に取り入れております。  

takaking22様のチームもモブプログラミングを実践しており、その手法を利用して新人研修を開催した実績があるとのことですが、  
是非このようなコラボレーションが出来ないか、一度相談させていただけないでしょうか。  

弊社オフィスは渋谷にありますので、理想的には訪問していた抱くことをお願いしたいと考えております。また、それが難しければスカイプ等でも構いません。

以上宜しくお願いいたします。

近藤

*（ちなみに、チーム採用ということですが、そもそもチーム名ってあるんですか）*

**Comment by TsubasaK111** [comment]
あげ  
（返事お待ちしております何卒よろしくお願い申し上げます）

**Comment by TAKAKING22** [comment]
ご連絡ありがとうございます。そしてお返事が遅れてしまい、大変申し訳ございません。

いただいたオファーをチームで検討させていただきましたが、今回我々が求めている機会とは少し異なるように思いますので、大変恐縮ではございますが今回はお断りをさせて下さい。別の形でコラボレーションさせていただける可能性はあるかと思いますが、現段階では転職を優先させて下さい。

魅力的なお声がけをいただき、近藤様には感謝しております。ありがとうございました。
