### ISSUE TITLE
FA宣言読みました。チームでまるっと来ませんか？

### ISSUE THREAD

**Issue by Taka-bow** [TAKAKING22/team-resume#2]
## 会社名
[ウイングアーク１ｓｔ株式会社](http://www.wingarc.com/)

## ご担当者様氏名
ソフトウェアプロセス＆品質改善部　[高橋裕之](https://www.scrumalliance.org/community/profile/htakahashi4)

## 条件
- チーム転職可、もちろん個別転職も可
- 勤務地：東京（六本木一丁目）
- フレックス可、 在宅ワーク可（基本週１）、育児休暇あり
- 給与レンジ：〜900万円、要相談（現在の額が不明なので）
- 就業中のタバコ禁止（休み時間はOK）
- その他、気になるところあればお答えします。

## コメント
ウイングアーク１ｓｔのプロダクトは内製を基本としています。ですので自分たちの責任でQCDSをマネジメント出来ます。
現在、新規プロダクトを開発中ですが、そこにアサイン出来るのではないかとコンタクトとらせていただきました。
ご検討頂けると幸いです。

**Comment by Taka-bow** [comment]
追加情報です。本日、発表いたしました。
http://www.wingarc.com/public/detail.php?pre=on&id=871
ぜひ、お力をお貸し願いたい。引き続き、ご検討宜しくおねがいします。

**Comment by Taka-bow** [comment]
6日経過しました。もし特にお返事頂けないようでしたら、クローズと致します。
明日まで待ってみます。
どうぞよろしくおねがいします。

**Comment by TAKAKING22** [comment]
ご連絡ありがとうございます。そしてお返事が遅れてしまい、大変申し訳ございません。

Github以外からもオファーをいただいており、チームで検討して順々にご対応させていただいております。
検討の結果、大変恐縮ではございますが今回はお断りをさせて頂く決断に至りました。魅力的なお声がけをいただき、高橋様には感謝しております。ありがとうございました。

**Comment by Taka-bow** [comment]
お返事ありがとうございます！
畏まりました。
残念ではございますが、皆様チームの次の活躍を心待ちにしております。
皆さんに触発され、最近当社でもモブプロをやり始めました。
コミュニティ等での今後の情報発信も楽しみ待ってますので、次のステージでも頑張ってください！
では、またどこかで。
